(function(){function n(a,d,f,g){if(!(a instanceof Node)&&(!a&&this.__xs__&&(a=this),a)){var p=!!a.__xs__;f&&(g=g&&g.concat()||[],g.push(f));d=D(d,a,g);var q=u(a).v,l;for(l in q)l in a||(delete q[l],G("delete",a,l,null,null));for(l in a)!p||l in q||G("add",a,l,a[l],null),H(a,l,d,g);Array.isArray(a)&&v(a,d);a.__observe__||void 0!==g||void 0!==f||y(a,"__observe__",n);return a}}function r(a,d){if(a.__xs__){for(var f=a.__xs__.h,g=f.length-1;0<=g;g--)f[g].f===d&&f.splice(g,1);for(var p in a)"object"===
typeof p&&null!==p&&r(p[a],d)}}function v(a,d){if(!a.__xs__.arrhelpers){a.__xs__.arrhelpers=!0;for(var f=function(d){var f=Array.prototype[d];y(a,d,function(){var a=this.__xs__;a.pause=!0;var g=f.apply(this,arguments);a.pause=!1;G(d,this,arguments,this,null);A(a.s,this,n);return g})},g="pop push shift unshift splice reverse sort".split(" "),p=0;p<g.length;p++)f(g[p])}}function u(a){if(!a.__xs__){var d={s:"@"+k++,v:{}};y(a,"__xs__",d)}return a.__xs__}function H(a,d,f,g){var p=u(a),q=p.v;f!==a&&(f=
D(f,a));var l=a[d];d in q||(q[d]=l,Object.defineProperty(a,d,{get:function(){return q[d]},set:function(l){var E=q[d];q[d]=l;"object"!==typeof l||null===l||l.__xs__||A(p.s,a,function(){n(l,f,{o:a,p:d},g)},!0);G("set",a,d,l,E);return l},enumerable:!0,configurable:!0}));"object"===typeof l&&n(l,f,{o:a,p:d},g)}function D(a,d,f){if(a===d||!a)return d;a="object"===typeof a?u(a).h:[{rootobj:d,f:a,path:f,s:"#"+M++}];var g=u(d);g=g.h=g.h||[];N(g,a,f);return d}function N(a,d,f){if(a!==d)for(var g=f||"",p=0;p<
d.length;p++){var q=d[p].s;a[q]||(void 0===g&&(g=f.reduce(function(a,d){return a+(a&&".")+d.p},"")),a[q]=!0,a.push({f:d[p].f,s:d[p].s,path:f,dotpath:g}))}}function K(a,d){if(d===a.obj)return a.prop;for(var f=a.chain,g=0;g<f.length;g++)if(f[g].o===d)return f[g].p;return null}function G(a,d,f,g,p){var q=d.__xs__;if(q&&q.h&&!q.pause){q=q.h;for(var l=0;l<q.length;l++){var k=q[l];k.f.call(d,{rootobj:k.rootobj,obj:d,action:a,prop:f,value:g,prev:p,chain:k.path,path:k.dotpath?k.dotpath+"."+f:void 0,find:K})}}}
function F(a,d){if(void 0===d)return a;if("object"!==typeof d||null===d)return d;var f=Object.prototype.toString.call(d);if("[object RegExp]"===f||"[object Date]"===f||d instanceof Node)return d;if("[object Array]"===f){"[object Array]"!==Object.prototype.toString.call(a)&&(a=[]);f=[];for(var g in d)g in a||(f[g]=d[g]);for(g in f)a[g]=f[g];return a}"object"!==typeof a&&(a={});for(var p in d)a[p]=F(a[p],d[p]);return a}function y(a,d,f,g){Object.defineProperty(a,d,{value:f,enumerable:!1,configurable:!0,
writable:!!g});return f}function C(){B=null;var a=z;z={};for(var d in a)a[d]&&a[d].f.call(a[d].o,a[d].o)}function A(a,d,f,g){if(B)return a in z||g?z[a]={f:f,o:d}:(f.call(d,d),z[a]=null),!1;g?z[a]={f:f,o:d}:f.call(d,d);B=setTimeout(C,0);return!0}var k=0,M=0,B,z={},w=window;w.xs=w.xs||{};w.xs.observe=n;w.xs.unobserve=r;w.xs.alias=function(a,d,f,g,p){var k=function(f){f.chain&&f.chain.length&&f.chain[0].p===g?(1===f.chain.length&&a[d]!==f.obj&&(a[d]=f.obj),f.chain[0].p=d,p(f),f.chain[0].p=g):f.chain||
f.prop!==g||(f.value!==a[d]&&(a[d]=f.value),f.prop=d,p(f),f.prop=g)};if(f instanceof Node){d in a||(a[d]=a[d]);a.__observer__||xs.observe(a);var l=Object.getOwnPropertyDescriptor(a,d);Object.defineProperty(a,d,{get:function(){return f[g]},set:function(a){f[g]=a;return l.set(a)},enumerable:!0,configurable:!0});return null}g in f||(f[g]=f[g]);xs.observe(f,k);a[d]=f[g];xs.observe(a);var n=Object.getOwnPropertyDescriptor(f,g);Object.defineProperty(a,d,{get:n.get,set:n.set,enumerable:!0,configurable:!0});
return k};w.xs.assign=function(){for(var a=arguments,d=0,f=a[0];++d<a.length;)f=F(f,a[d]);return f};w.xs.clone=function(){for(var a=arguments,d=-1,f={};++d<a.length;)f=F(f,a[d]);return f};w.xs.debounce=A;w.xs.privateprop=y}).call(this);var legacy=!document.currentScript,rf_script=null;
window.reeferHTML=function(n){n&&n.constructor&&n.call&&n.apply&&(n=n.toString().split("\n").slice(1,-1).join("\n"));var r=legacy?null:document.currentScript;r||(r=rf_script);r||(r=document.getElementsByTagName("script"),r=r[r.length-1]);rf_script=null;var v=r.reefCB;void 0===v?r.outerHTML=n:v(n);r.parentNode&&r.parentNode.removeChild(r)};
ReeferFactory=function(n){function r(){console.error(arguments)}function v(){console.error(arguments);throw Error("REEF FAULT");}function u(b,c){b[c]=b[c]||{};return b[c]}function H(b){b=b||document;for(var c=[],m=b.querySelectorAll(":not([reef-stage])[reef]"),e=0;e<m.length;e++)if(!m[e].reef){a:{var a=m[e],d=b.reef;if(a){var h=a.getAttribute("reef");try{for(var f,g=void 0,k=a.attributes,p=0;p<k.length;p++){var l=k[p],q=l.name+"";if(0===q.indexOf("reef-p")){g=g||{};var n=l.value,v=q[6],t=n.split(v+
v);n=t[0];t=t[1];var w=q.substring(7);if("~"!==n[0])var y=!1;else{var z=n.split("~");y={prop:z[1],selector:2>z.length?"^":z[2]}}try{n=JSON.parse(n)}catch(L){}y?u(g,"bind")[w]=y:u(g,"props")[w]=n;t&&(u(g,"events")[w]=t)}else if(0===q.indexOf("reef@")){var G=q.substring(5);g=g||{};u(g,"listeners")[G]=l.value}}f=g;var A=a.cloneNode(!0);if(A&&(f=f||{},A.children))for(g=0;g<A.children.length;g++){var F=u(f,"slots"),x=A.children[g],C=x.getAttribute,H=C&&C.call(x,"reef-slot")||"default",J=F[H]=F[H]||[];
J.push(x);J.text=(J.text||"")+(C?x.outerHTML:x.data);if("SCRIPT"===x.nodeName&&0===x.type.indexOf("reef-")){try{var I=x.getAttribute("type"),B=I.match(/\(([^)]*)\)/);B=B?B[1]:"";var D=x.innerHTML.trim();if(D)switch(I.split("(")[0].trim()){case "reef-function":x.reefScript=new Function(B,D);break;case "reef-template":x.reefScript=P(B,D);break;default:r("unknown reef slot type")}}catch(L){r("reef-slot script parsing ERROR:",D||x.type,x,L)}"el"in J||(J.el=x);"script"in J||!x.reefScript||(J.script=x.reefScript)}}var E=
K(a,h,f,d);break a}catch(L){r("Reefer failed to mount: ",h,a,L)}}E=null}E&&E.render_();c.push(E)}return c}function D(b,c){return new Function(b,"return `"+c+"`;")}function N(b,c){c=c.split("\n").join("\\\n").replace(/"/g,'\\"');return new Function(b,'var f=function (_, exp) {return eval(exp)}; f.bind(this); return "'+c+'".replace(/\\${(.*?)}/g, f)')}function K(b,c,m,e){m=m||{};t[c]||v("Reefer NOT registered: ",c);m=b.reef=new n.use(b,t[c],m);m.name=c;b.setAttribute("reef-stage","mounted");if(m.listeners){b=
m.listeners;for(var a in b)c=a.split("@"),e=c[0],O[e]||(O[e]=G(e),document.addEventListener(e,O[e],!1)),b[e]=b[a],"stop"===b[c[1]]&&(b[e].reefStop=!0);m.listeners=null}return m}function G(b){return function(c){for(var m=c.detail&&c.detail.reefEmitRootEl||c.target,e,a="reef@"+b,d=[];m;){var h=m.getAttribute&&m.getAttribute(a);h&&(h=h.split("@"),d.push(h));h=m.reef;c.reef||(c.reef=h);if(h&&d.length)for(e=0;e<d.length;e++){var f=d[e],g=f[0].trim(),p=g.match(/\(([^)]*)\)/);if(p=(p&&p[1]||"").split(",")){g=
g.split("(")[0];var k=p.indexOf("$event");0<=k&&(p[k]=c)}k=h.dotpath(g);var l;if(void 0!==k.value&&(y(k.value)?l=k.value.apply(k.obj,p||[c]):h.dotpath(g,p[0]),"stop"===l||"stop"===f[1]))return}e=h&&h.name;if(t[e]&&(e=t[e],e.listeners&&e.listeners[b]&&("stop"===e.listeners[b].call(h,c)||e.listeners[b].reefStop)))break;m=m.parentNode}}}function F(b,c){return"string"!==typeof b?b:F(c||document).querySelector(b)}function y(b){return!!(b&&b.constructor&&b.call&&b.apply)}function C(b,c){if(!Array.isArray(b))return b;
for(var m={},e=0;e<b.length;e++)m[b[e]]=1>=arguments.length?!0:c;return m}function A(b,c,m,e){for(var a=0;a<c.length;a++){var d=c[a],h=d in e?e[d]:m[d];void 0!==h&&(b[d]=xs.clone(h))}}function k(b,c,m){c=c||{};m=m||{};var e=this,a=this.__={};A(a,["template","update","bind"],c,m);A(this,["methods","observers","listeners","mutate"],c,m);"shared"in c&&(this.shared=c.shared);if(c.events||m.events)a.events=xs.assign({},C(c.events),m.events);if(c.decorators||m.decorators)a.decorators=xs.assign({},C(c.decorators),
C(m.decorators));(c.slots||m.slots)&&xs.assign(u(this,"slots"),c.slots,m.slots);"super"in c&&(this["super"]=t[c["super"]]);var d=this.methods;if(d)for(var h in d)d[h]=y(d[h])?d[h].bind(e):d[h];this.rootEl=b;a.obsf=function(){k.prototype.react.apply(e,arguments)};b=this.data=xs.observe({},a.obsf);xs.assign(b,a.decorators,c.data,m.props);for(h in this.observers)h in b||(b[h]=void 0);for(h in a.bind)w(this,"data."+h,a.bind[h].selector,a.bind[h].prop);b.__observe__();this.sym="$"+Q++;return this}function M(b,
c,m){var e=this;m=m||{};e=this;var a=m.xhr||new XMLHttpRequest;a.onerror=function(b){console.log("REEF HTTP LOAD",b);I(e.rootEl,"reefLoadDataFail",{url:c})};a.onload=function(c){if(200==this.status){c=this.response;try{c=JSON.parse(c)}catch(h){}e.dotpath(b,c)}else if(this.status)a.onerror(c)};a.open(m.method||"GET",c,!0);a.send(null);return a}function B(b,c){var a=this;if("loading"!==document.readyState){var e=document.createElement("script");e.src=c;document.getElementsByTagName("head")[0].appendChild(e)}else document.write('<script src="'+
c+'">\x3c/script'),e=document.getElementsByTagName("script"),e=e[e.length-1];e.onerror=function(b){console.log("REEF SCRIPT LOAD",b);e.parentNode.removeChild(e);I(a.rootEl,"reefLoadHTMLFail",{url:c})};e.reefCB=function(c){a.dotpath(b,c)};return rf_script=e}function z(b,c){sp=q(b,c);if(sp.obj)return sp;for(var a=c.split("."),e=b,d=0;d<a.length;d++){var f=e[a[d]];if(void 0===f||null===f||"object"!==typeof f)e[a[d]]=d==a.length-1?void 0:{};e=e[a[d]]}return q(b,c)}function w(b,c,a,e,d){a=a||"^";var m=
u(b.__,"bind"),h=u(m,c);e=e||c;if(h.proppath!==c||h.selector!==a||h.prop!==e){switch(a[0]){case "^":var f=z(b,e);break;case "#":case ".":case "[":(f=(d=(d||document).querySelector(a))&&d.reef)||v("unable to locate reef for bind");f=z(f,e);break;case "$":switch(d=a.substring(1,6),h=a.substring(6),m[c]={proppath:c,selector:a,prop:e},d){case "json:":return M.call(b,c,h);case "html:":return B.call(b,c,h)}default:v("unknown data bind: "+c+": "+a)}d=q(b,c);d.obj||v("data bind not found: "+c);d=xs.alias(d.obj,
d.key,f.obj,f.key,function(c){b.rootEl&&b.rootEl.getRootNode()===document?b.react(c):b.unmount()});m[c]={proppath:c,selector:a,prop:e,sp:f,unobs:d}}}function a(){var b=new Date,c=this.rootEl;if(c&&c.getRootNode()===document){var a=this.__.template;if(a){var e=this.__.fcounter;e&&this.htmlBegin();e=this.__.fcounter;a=a.call(this,this.slots)||"";this.__.harr?this.htmlEnd():"string"===typeof a?"done"!==a&&(c.innerHTML=a):(c.innerHTML="",Array.isArray(a)?a.forEach(function(b){c.appendChild(b)}):c.appendChild(a));
c.parentNode.classList.contains("container");H(c);c.parentNode.classList.contains("container")&&console.log("render",new Date-b)}}else this.unmount()}function d(){var b=l(this.rootEl);a.call(this);b()}function f(b){switch(b.nodeName){case "TABLE":return b.childNodes?b.childNodes[0]:b;default:return b}}function g(b){for(var c=0,a=b.length,e=0;e<a;e++){var d=b.charCodeAt(e);c=(c<<5)-c+d;c|=0}return c}function p(b,c){if(3===b.nodeType)return b.nodeValue!==c.nodeValue&&(b.nodeValue=c.nodeValue),!0;if(b.childNodes.length||
c.childNodes.length){for(var a,e=b.childNodes,d=c.childNodes,f=a=Math.min(e.length,d.length);0<=--a;){var h=e[a],g=d[a];h.isEqualNode(g)||h.nodeName===g.nodeName&&p(h,g)||b.replaceChild(g,h)}for(;f<e.length;)b.removeChild(e[f++]);for(;f<d.length;)b.appendChild(d[f++])}if(c.hasAttribute){a:{try{a={};var k=c.attributes;for(e=0;e<k.length;e++){var l=k[e];a[l.name]=!0;b.getAttribute(l.name)!==l.value&&b.setAttribute(l.name,l.value)}var n=b.getAttributeNames();if(n.length===k.length){var q=!0;break a}for(e=
0;e<n.length;e++)l=n[e],a[l]||b.removeAttribute(l);q=!0;break a}catch(S){}q=!1}return q}return!0}function q(b,c,a){"string"===typeof b&&(a=c,c=b,b=this);for(var e=b,d=c.split("."),m=d.length,f=b,g,k=0;k<m&&(void 0!==b||!k);k++)g=d[k],b=(f=b)&&g in b?b[g]:void 0;if(arguments.length>(e===this?1:2)){if(k!==m)throw Error("full chain path does not exist");f[g]=a}e={value:b,key:g,obj:f};return k===m?e:{last:e}}function l(b){var c=document.activeElement;if(c)for(var a=c.selectionStart,e=c.selectionEnd,d=
[];c&&c!==b&&c.parentNode;)d.push([].indexOf.call(c.parentNode.childNodes,c)),c=c.parentNode;return function(){if(c){for(c=b;c&&d.length;){var m=d.pop();c=c.childNodes[m]}if(c){c.focus&&c.focus();try{c.selectionStart=a,c.selectionEnd=e}catch(h){}}}}}function I(b,c,a){b=F(b);a=a||{};b&&(a.reefEmitRootEl=b);document.dispatchEvent(new CustomEvent(c,{detail:a}))}function E(b){"complete"===document.readyState||"loading"!==document.readyState&&!document.documentElement.doScroll?b():document.addEventListener("DOMContentLoaded",
b)}n=n||{};var Q=0,O={},R=0,t={"":{template:function(){var b=this.slots||{};if(b["default"]){if(!this.data.datasrc)return"done";var c=this.data,a="datactx"in c?this.dotpath(c.datactx).value:{},e="datasrc"in c?this.dotpath(c.datasrc).value:this,d=this.data.genkey,f=e&&b[c.dataslot||"default"]||b.empty&&b.empty.text||{text:"<div> </div>"};c=c.datakey;var h;Array.isArray(e)||(e=[e]);b.header&&this.html(-1,b.header.script?b.header(a):b.header.text);for(var g=0;g<e.length;g++){var k=typeof e[g];e[g]&&
(h=void 0===c?e[g].__key__:e[g][c]);d&&void 0===h&&"object"===k&&(h=xs.privateprop(e[g],"__key__","k"+R++));k=f.script?f.script(e[g],g,a):f.text;this.html(h||g,k)}b.footer&&this.html(-2,b.footer.script?b.footer(a):b.footer.text)}}}};k.prototype.unmount=function(){var b=this.__||{};xs.unobserve(this.data,b.obsf);if(b.bind)for(var c in b.bind){var a=b.bind[c];a.obsf&&xs.unobserve(a.sp.obj,a.obsf)}};k.prototype.react=function(b){b.reef=this;var c=this.__,a=b.root=b.path?b.path.split(".")[0]:b.prop,e=
this.observers;if(e){var d;if(!(d=c.obsrx)){d="";for(var f in e)d+=":xs:"+f+"\n"}c.obsrx=d;if(b.path&&(f="(:xs:(("+b.path.replace(/\./g,"\\.)|(\\*\\.))*((")+")|(\\*)))\n",f=c.obsrx.match(new RegExp(f,"g")))){var g=f[0];for(a=1;a<f.length;a++)f[a].length>g.length&&(g=f[a]);a=g.substring(4,g.length-1)}if(e=e[a])if(y(e))var k=e.call(this,b);else b.path||"set"!==b.action&&"add"!==b.action||(e=this.dotpath(e),y(e.value)?e.value.call(this):e.obj[e.key]=b.value)}(e=c.events)&&e[a]&&I(this.rootEl,c.name+
"."+(!0===e[a]?a:e[a]),b);var l;b.value!==b.prev&&(this.mutate&&(l=this.mutate.call(this,b)),b=c.decorators,this.sym&&("done"===k||"done"===l||b&&(b[a]||b[g])||this.rerender()))};k.prototype.observe=function(b,a){u(this,"observers")[b]=a;this.__.obsrx=null};k.prototype.decorate=function(b,a){u(this,"decorators")[b]=!1!==a&&0!==a};k.prototype.events=function(b,a){u(this.__,"events")[b]=!1!==a&&0!==a&&a;this.__.evrx=null};k.prototype.watch=function(a,c){this.data[a]=c;this.data.__observe__()};k.prototype.bind=
function(a,c,d,e){w(this,a,c,d,e)};k.prototype.emit=function(a,c){I(this.rootEl,a,c)};k.prototype.render_=a;k.prototype.render=function(){xs.debounce(this.sym+"_rr",this,a)};k.prototype.rerender=function(){xs.debounce(this.sym+"_rr",this,d,!0)};k.prototype.htmlBegin=function(a){if(!this.__.harr||a)this.__.hmap={},this.__.hgeneration=-1;this.__.harr=[];this.__.hgeneration++;this.__.fcounter=0};k.prototype.htmlUpdate=function(a,c,d){var b=this.__.hmap;if(b){var m=g(d);c=void 0===c||null===c?m:c;c in
b||v("updateing non-existent element");if(b[c].hsh!==m||a!==b[c].idx){var k=f(this.rootEl)||this.rootEl,h=b[c].el;h.getAttribute?(b[c].hsh=m,b[c].idx=a,c=b[c],a=k.childNodes[a],b=(k=a.previousSibling)||a.parentNode,a.getAttribute?a.outerHTML=d:a.nodeValue=d,c.el=k?k.nextSibling:b.childNodes[0]):h.nodeValue!==d&&(h.nodeValue=d)}}};k.prototype.htmlEnd=function(){var a=this.__,c=a.hgeneration,d="",e=a.harr,g=a.hmap;if(e){a=this.__.fcounter;var k=null;if(0===a)this.htmlBegin(!0),this.rootEl.innerHTML=
"";else{if(0===c||0===a)this.rootEl.innerHTML="";for(var h in g){var l=g[h];l.generation!==c&&(l.el&&l.el.parentNode.removeChild(l.el),delete g[h])}c=f(this.rootEl)||this.rootEl;g=document.createElement(c.nodeName);l={};var n="",q=0;for(h=0;h<a;h++){var r=e[h];r.h?(l[h]=q++,n+=r.h):l[h]=null}q&&(g.innerHTML=n);for(h=q=0;h<a;h++){n=e[h].el;if(r=e[h].h){if(h>=c.childNodes.length)d+=r;else if(n){e[h].el=g.childNodes[l[h]-q++];r=e[h];var t=n;var u=e[h].el;t.nodeName===u.nodeName&&p(t,u)||(t.parentNode.replaceChild(u,
t),t=u);r.el=t;e[h].el===n&&q--}else g.innerHTML=r,e[h].el=g.childNodes[0];e[h].h=null}0!==h&&null===k&&e[h].el&&v("htmlEnd() logic error");n=e[h].el;!n||n.parentNode===c&&n.previousSibling===k||(k?k.parentNode.insertBefore(n,k.nextSibling):c.childNodes&&c.childNodes[0]===n||c.insertBefore(n,c.childNodes&&c.childNodes[0]));k=n}e.length=a;d&&c.insertAdjacentHTML("beforeend",d);if((c=f(this.rootEl))&&e.length!=c.childNodes.length){console.error("must be 1 html() entity for hmtl()");debugger}g={};for(h=
0;h<e.length;h++)g[e[h].id]=e[h],e[h].el=c.childNodes[h],e[h].idx=h;return"done"}}};k.prototype.htmlKeyToIdx=function(a){var b=this.__.hmap;return b&&b[a]?b[a].idx:null};k.prototype.html=function(a,c){this.__.harr||this.htmlBegin();var b=this.__,d=b.harr,f=b.hmap,k=b.fcounter++;b=b.hgeneration;var h=g(c);a=void 0===a||null===a?h:a;f[a]?(f=f[a],f.generation===b&&v("duplicate html() id"),f.generation=b,d[k]=f,f.hsh!==h&&(f.h=c,f.hsh=h)):(b={h:c,hsh:h,idx:k,id:a,generation:b},d.splice(k,0,b),f[a]=b)};
k.prototype.dotpath=q;k.prototype.styleBag=function(a){var b=this.rootEl,d=g(JSON.stringify(a));if(b.__xs__style!==d){for(var e in a)b.style[e]=a[e];b.__xs__style=d}};n.autorun&&E(function(){H()});n.use=n.use||k;var P=legacy?N:D;return{register:function(a,c,d){var b="*"===a[0]?a.substring(1):a;d=d||"";c.data=C(c.data,void 0);if(t[b])a===b&&v("Reefer already registered: "+b);else return t[d]||v("Super Reef NOT registered: "+d),t[b]=xs.assign({},t[d],c),t[b].name=b,t[b]["super"]=d,!0},mount:K,run:H,
template:P,ready:E,emit:I,registry:function(a){return a?t[a]:t},find:function(a,c){return(a=this.findAll(a,c))?a[0]:null},findAll:function(a,c){a=[].slice.call((c||document).querySelectorAll(a));var b=0;if(a)for(var d=0;d<a.length;d++)a[b]=a[d].reef,b+=a[b]?1:0;return b?(a.length=b,a):null}}};window.reefer=ReeferFactory({autorun:!0});